const XLSX = require('xlsx');
const path = require('path');
const fs = require('fs');

const EXCEL_PATH = path.resolve(__dirname, '../The FullMoon Festival Linup.xlsx');
const OUTPUT_PATH = path.resolve(__dirname, '../data/lineup.js');

const STAGE_ORDER = [
  'Outdoor Main Stage',
  'Bunka',
  'Groove2Funk',
  'ReVival',
  'Hot Wax',
  'Volume',
  'RoomTour',
  'The Pub'
];

// Normalise stage names from spreadsheet to canonical names
const STAGE_MAP = {
  'outdoor main stage': 'Outdoor Main Stage',
  'bunka': 'Bunka',
  'groove2funk': 'Groove2Funk',
  'g2f': 'Groove2Funk',
  'revival': 'ReVival',
  'hot wax': 'Hot Wax',
  'hotwax': 'Hot Wax',
  'volume': 'Volume',
  'roomtour': 'RoomTour',
  'room tour': 'RoomTour',
  'the pub': 'The Pub',
  'pub': 'The Pub'
};

function normaliseStage(raw) {
  if (!raw) return null;
  const key = String(raw).trim().toLowerCase();
  return STAGE_MAP[key] || String(raw).trim();
}

// Excel stores times as decimal fractions: 0 = midnight, 0.5 = noon
function excelTimeToString(val) {
  if (val === null || val === undefined || val === '') return null;
  const num = typeof val === 'number' ? val : parseFloat(val);
  if (isNaN(num)) return null;
  const totalMinutes = Math.round(num * 24 * 60);
  const hours = Math.floor(totalMinutes / 60) % 24;
  const minutes = totalMinutes % 60;
  return `${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}`;
}

function normaliseDay(raw) {
  if (!raw) return null;
  const s = String(raw).trim().toLowerCase();
  if (s === 'friday') return 'Friday';
  if (s === 'saturday') return 'Saturday';
  if (s === 'sunday') return 'Sunday';
  return null;
}

function normaliseType(raw) {
  if (!raw) return 'DJ';
  const s = String(raw).trim().toLowerCase();
  if (s.includes('band')) return 'Band';
  return 'DJ';
}

function main() {
  if (!fs.existsSync(EXCEL_PATH)) {
    console.error('ERROR: Excel file not found at', EXCEL_PATH);
    process.exit(1);
  }

  const workbook = XLSX.readFile(EXCEL_PATH);
  const sheetNames = workbook.SheetNames;
  console.log('Sheets found:', sheetNames);

  // Sheet 2 is the master database (index 1)
  const sheetName = sheetNames[1];
  console.log('Reading sheet:', sheetName);

  const sheet = workbook.Sheets[sheetName];
  const rawRows = XLSX.utils.sheet_to_json(sheet, { defval: '' });

  // Normalise all column keys by trimming whitespace
  const rows = rawRows.map(row => {
    const clean = {};
    for (const [k, v] of Object.entries(row)) clean[k.trim()] = v;
    return clean;
  });

  console.log(`Total rows in sheet: ${rows.length}`);
  if (rows.length > 0) {
    console.log('Columns detected:', Object.keys(rows[0]));
  }

  const acts = [];
  let skipped = 0;

  for (const row of rows) {
    const name = String(
      row['Name of Act'] || row['Name On Poster'] || row['Name on Poster'] || row['name'] || ''
    ).trim();

    const stageRaw = row['Stage Name'] || row['Stage'] || '';
    const dayRaw = row['Day Act is On'] || row['Day'] || '';
    const startRaw = row['Time Start'] || row['Start'] || '';
    const stopRaw = row['Time Stop'] || row['Stop'] || row['End'] || '';
    const typeRaw = row['Description - Band or DJ'] || row['Description'] || row['Type'] || '';

    const day = normaliseDay(dayRaw);
    const stage = normaliseStage(stageRaw);
    const start = excelTimeToString(startRaw);
    const end = excelTimeToString(stopRaw);

    if (!name || !day || !stage || !start || !end) {
      skipped++;
      continue;
    }

    acts.push({
      name,
      stage,
      day,
      start,
      end,
      type: normaliseType(typeRaw)
    });
  }

  // Sort: by day order, then by stage order, then by start time
  const dayOrder = { Friday: 0, Saturday: 1, Sunday: 2 };
  acts.sort((a, b) => {
    const dayDiff = (dayOrder[a.day] ?? 9) - (dayOrder[b.day] ?? 9);
    if (dayDiff !== 0) return dayDiff;
    const stageDiff = (STAGE_ORDER.indexOf(a.stage)) - (STAGE_ORDER.indexOf(b.stage));
    if (stageDiff !== 0) return stageDiff;
    return a.start.localeCompare(b.start);
  });

  // Report stages actually found in the data
  const stagesFound = [...new Set(acts.map(a => a.stage))];
  const stagesFinal = STAGE_ORDER.filter(s => stagesFound.includes(s));
  // Add any unlisted stages at the end
  for (const s of stagesFound) {
    if (!stagesFinal.includes(s)) stagesFinal.push(s);
  }

  const output = {
    festival: 'Full Moon Festival',
    dates: {
      Friday: '26 June 2026',
      Saturday: '27 June 2026',
      Sunday: '28 June 2026'
    },
    stages: stagesFinal,
    acts
  };

  const jsContent = `// Generated by scripts/convert.js — do not edit manually
// Source: The FullMoon Festival Linup.xlsx
// Run "node scripts/convert.js" to regenerate

const LINEUP_DATA = ${JSON.stringify(output, null, 2)};
`;

  fs.writeFileSync(OUTPUT_PATH, jsContent, 'utf8');

  console.log(`\nDone.`);
  console.log(`  Acts written: ${acts.length}`);
  console.log(`  Rows skipped: ${skipped}`);
  console.log(`  Stages: ${stagesFinal.join(', ')}`);
  console.log(`  Output: ${OUTPUT_PATH}`);
}

main();
